version: '3.5'
services:
 web_dev:
  build: .
  ports:
   - "4000:4000"
  volumes:
   - .:/mon_petit_film
  environment:
   - ENV=development
   - PORT=4000
   - DB=mongodb://barth:mybigmovie123@ds113799.mlab.com:13799/heroku_1hj3v1h2
networks:
 default:
  name: web_dev